replace old prepwork links and language
appacademy-prep-work/appacademy-prep-work.github.io pull request #15
Opened 2018-11-09 04:18 UTC by azablan

2018-11-09 04:31 UTC, wolverdude requested changes

2018-11-09 04:31 UTC, wolverdude commented on _includes/technical-interview.md
>  Keep the following in mind when approaching problems:
Why keep this line? It's now meaningless.

2018-11-09 04:31 UTC, wolverdude commented on _includes/technical-interview.md
>  Read our [introduction to pair programming][pair-programming]. Your interview
Do we have updated material on pair programming, or is this link still current?

2018-11-23 17:24 UTC, alvin-the-programmer commented on _includes/technical-interview.md
>  Read our [introduction to pair programming][pair-programming]. Your interview
That is current, there is no other version of this.

2018-11-23 17:26 UTC, alvin-the-programmer commented on _includes/technical-interview.md
>  Keep the following in mind when approaching problems:
removed

2018-11-23 17:28 UTC, merged

2018-11-23 23:28 UTC, wolverdude commented
Thanks!