Ruby Monk deletion
appacademy-prep-work/appacademy-prep-work.github.io pull request #8
Opened 2016-10-26 21:50 UTC by chungkikelly

Added Code Fights in one of the document. Cool site.

Should I add more resources throughout the website?

2016-10-27 16:24 UTC, wolverdude approved these changes

2016-10-27 16:25 UTC, wolverdude requested changes
It's not enough just to remove RubyMonk. We should replace it with something else. At present, that would be the CodeAcademy course, unless you have a better suggestion.

2016-10-27 16:28 UTC, wolverdude commented on _includes/additional-practice.md
> +[code-fights]: https://codefights.com/
This page is deprecated. You can keep the updates, but you should also add Code Fights to the [interview prep page](https://github.com/appacademy-prep-work/appacademy-prep-work.github.io/blob/master/_includes/technical-interview.md).

2016-11-03 01:53 UTC, chungkikelly commented
Made necessary changes to files.

2016-11-03 16:18 UTC, wolverdude approved these changes

2016-11-03 16:18 UTC, merged